### ISSUE TITLE
Deep-cloning state is an anti-pattern

### ISSUE THREAD

**Issue by markerikson** [anish000kumar/redux-box#1]
Per the [Redux FAQ entry on deep-cloning state](https://redux.js.org/docs/faq/Performance.html#performance-clone-state), deep cloning is bad for performance due to the cost of copying all fields, and the new references causing unnecessary re-rendering.  

If you want to provide a way for reducer functions to update state safely with normal mutative code, I'd suggest looking at the [`immer` library](https://github.com/mweststrate/immer) instead.

**Comment by anish000kumar** [comment]
@markerikson Yes, I had this issue in my mind and was trying out a couple of ways to get around this. immer looks like a great choice. Thanks for the heads up!

**Comment by anish000kumar** [comment]
# The latest release has this issue resolved.
