### ISSUE TITLE
Babel-polyfill may collide in apps that already have it defined

### ISSUE THREAD

**Issue by rob-curl-vertexinc** [anish000kumar/redux-box#10]
I was hoping to use this for an app I'm working on for a client. Unfortunately a necessary internal dependency includes babel-polyfill, and resulting in the following error 
`Error: only one instance of babel-polyfill `

Babel even suggests not to use babel-polyfill for libraries for this reason.
https://github.com/babel/babel/issues/3832
https://babeljs.io/docs/usage/polyfill/#details

**Comment by anish000kumar** [comment]
This issue will be resolved in upcoming releases to come in few days. For the moment, however, you may actually skip adding babel-polyfill from your side. one instance of babel-polyfill should work project-wide.

**Comment by rob-curl-vertexinc** [comment]
I actually did end up removing it from the other dependency in my attempts to debug the issue, but I'm only able to do this locally since I don't have access to the dependency's source repo. Once I commit my local dev branch and it hits the automated build, this issue will re-emerge. 

However, I think I can push that off a few days.
Thanks for the quick turn around 👍

**Comment by anish000kumar** [comment]
babel polyfill has been removed from the core package in v1.4.5 . You should now import it externally if needed.
