### ISSUE TITLE
Adding Redux Observable?

### ISSUE THREAD

**Issue by KyleMcNutt** [anish000kumar/redux-box#12]
I would love to see either an example of this with [redux-observable](https://github.com/redux-observable/redux-observable) (if possible) or have this added as a feature.

I _love_ this syntax for modules, and think it paired with redux-observable would be really amazing.

**Comment by zhDmitry** [comment]
+1 it would be awesome.

**Comment by janryWang** [comment]
[redux-callbag](https://github.com/janryWang/redux-callbag) You can try it, extremely lightweight, and highly scalable

**Comment by anish000kumar** [comment]
@KyleMcNutt @zhDmitry Using redux-observable should be as simple as setting up any middleware. Here's a working project to show how we can use redux-observable with redux-box
https://stackblitz.com/edit/react-zu8qjn?file=store%2Fuser%2Fepics.js
(Updated in the readme as well, for better reference)

**Comment by KyleMcNutt** [comment]
@anish000kumar That's great! Thank you for sharing that awesome example! Closing, since I think the ask here has been covered.
