### ISSUE TITLE
Reselect?

### ISSUE THREAD

**Issue by mbbender** [anish000kumar/redux-box#15]
I'm new to all this stuff but found your (a) video on redux-box and really like the way it looks compared to all the boilerplate. I also found this project: react-boilerplate which seems great. I see lots of mention of using reselect for performance reasons, but can't say I actually understand what it is doing yet. I'm wondering if you could address the ability to use reselect for performance or if maybe redux-box addresses this in another way.

**Comment by anish000kumar** [comment]
Reselect is a great way to get 'computed' properties out of your redux state.  To get a better understanding of how it works you should check out their official repository.

The current version of redux-box doesn't have any inbuilt API to let you use 'computed' properties, but Reselect can be pretty much used independently to achieve this at the moment. However, I have been working on the next major release for redux-box, in which you will have support for computed-properties (or getters or derived-properties) out of the box.

**Comment by anish000kumar** [comment]
Just an update, the latest beta release of redux-box (1.6.0) supports selectors/ getters out of the box. Simple usage can be seen in the readme, while for more detailed usage you may refer to the official docs for reselect (https://github.com/reactjs/reselect), which is being used under the hood.
