### ISSUE TITLE
Redux Saga effect 'select' doesn't work as expected

### ISSUE THREAD

**Issue by sazzer** [anish000kumar/redux-box#24]
Redux Box packages things nicely into modules, where each module is nicely self-contained.

This goes as far as having Selectors that exist as part of the module, and when called are only give this modules portion of the state. This is fantastic for building up self-contained modules easily.

Unfortunately, Redux Box relies on the Redux Sagas "effects" for some feature. One such feature is the obtaining values from elsewhere in the state during a Saga - using the `select` effect.

This effect works exactly the same as in Redux Saga. Which means that it calls the provided selector with the *entire* state tree and not just the local modules portion of it. Ultimately this means that we need to have two different types of selector - some that work on the local module and some that work on the entire state tree.

It could be useful to have a variation of `select` that applies the selector only to the local module state, so that the selectors used can remain consistent.

**Comment by anish000kumar** [comment]
@sazzer That's a great point actually. Ideally sagas should also have access to the module state without using `select` (much like mutations do). Unfortunately because of the busy schedule (and other OS projects), I've not been able to find much time for redux-box, it would be great if people from community start contributing as well.

**Comment by Nickman87** [comment]
How about passing in a second parameter to every saga in the 'createSagas' method which is an object, containing all saga effect but slightly modified to work with redux-box?
Maybe even scoped per registered module? (this also eliminates the need to manually import the effects)

```
import otherModule from './otherModule';

const sagas = createSagas({
  SET_EMAIL: function*(action, saga) {
    const data = yield saga[otherModule.name].select(otherModule.selectors.someSelector);
    const response = yield saga.call(api.updateEmail, action.email, data); // Identical to redux-saga imported 'call'
  }
});
```

**Comment by anish000kumar** [comment]
Latest release of redux-box i.e 2.0.0+ should address the concerns shared in this issue. There are breaking changes in this release however, so you would want to keep that in mind if upgrading for previous projects. For new projects, it should work just fine if you use latest version of redux-box.
