### ISSUE TITLE
How to invoke actions from sagas

### ISSUE THREAD

**Issue by jbrodriguez** [anish000kumar/redux-box#28]
I'm trying to figure out how to invoke actions from sagas

Should this work ?

```javascript
const state = {
	version: '1.0.0',
}

const actions = {
	setVersion: version => ({ type: 'SET_VERSION', payload: version }),
}

const mutations = {
	SET_VERSION: (state, action) => (state.name = action.payload),
}

const sagas = createSagas({
	GET_VERSION: function*(action) {
		const response = yield call(api.getVersion)
		yield put(actions.setVersion(response.version))
	},
})
```

But then what if I need to invoke an action from another module ?

Should I import the other module (or at least the other module's actions) ?

Any thoughts ?

P.D.: I've seen the saga example where you invoke put without the action creator ({type: ....}), but the idea of using the action creator is to have strong typing, whenever typescript becomes available.

**Comment by anish000kumar** [comment]
@jbrodriguez  Yes, you can simply import the actions object and use it the same way as used in your snippet above. You wouldn't want to import the whole module for this purpose. One handy practise you might follow though is  to import `actions` as const as well from store's index file:

```javascript
//userModule/index.js
import state from "./state"
import actions from "./actions"
import mutations from "./mutations"
import sagas from "./sagas"

export const module = {
state, 
actions,
sagas,
mutations
}

export { default as actions } from "./actions"

---
//cartModule/sagas.js
import { actions } from "@userModule"
```

**Comment by jbrodriguez** [comment]
Thanks, that makes sense 👍
