### ISSUE TITLE
make it compatible with react-redux v6.x.x

### ISSUE THREAD

**Issue by ramyareye** [anish000kumar/redux-box#33]
Hello,

Is it possible to upgrade package to support newer react-redux versions ? 
Current stable is 6.* and 7 is beta.
I need to use the newer version of https://github.com/rgommezz/react-native-offline and it needx react-redux 6.x.x to be installed.

Thanks

**Comment by anish000kumar** [comment]
latest version of redux-box should work fine i.e redux-box@2.0.0+. However, there are breaking changes in this release, so you would want to keep that in mind. Cheers!
