### ISSUE TITLE
Unable to resolve module `./helpers` from `node_modules/redux-box/dist/index.js`

### ISSUE THREAD

**Issue by josephJ2e** [anish000kumar/redux-box#34]
Hello,

I am upgrading redux-box from v1.6.2 to v2.0.0-beta.2 and then I got this error. Is there anybody encountered this error too? and how to fix? Thanks a lot!

Unable to resolve module `./helpers` from `node_modules/redux-box/dist/index.js`

**Comment by anish000kumar** [comment]
@josephJ2e Can you share the trace-log or a sandbox failing build (via codesandbox) ?

As a sidenote, Redux-Box@2+ API is not backward compatible with previous versions. So, you would need to use

**Comment by josephJ2e** [comment]
@anish000kumar I downgraded it back to v1.6.2 for now. And I think you are right because I did not do any changes of the code after upgraded. so I decided to still use v1.6.2 for now since I dont have the luxury time. I will upgrade this soon and do the necessary changes and will get back to you should have any issues encountered. Thanks a lot for your time to reply.
