### ISSUE TITLE
idea: replace screenshots with Markdown

### ISSUE THREAD

**Issue by hex13** [anish000kumar/redux-box#5]
I wonder why there are screenshots in Readme instead of text? It prevents e.g. copy-pasting (not to mention other aspects like overall accesibility, i.e. screen readers, poor connection, SEO etc.)

Markdown (at least in GH and NPM flavors) has syntax coloring out-of-the-box.
You write:
 \`\`\`javascript
import {createSagas, createCntainer } from 'redux-box'
\`\`\`

And it looks:

```javascript
import {createSagas, createCntainer } from 'redux-box'
```
https://guides.github.com/features/mastering-markdown/

**Comment by anish000kumar** [comment]
@hex13  thanks for raising the issue. It's been implemented.
