### ISSUE TITLE
Use with redux-persist

### ISSUE THREAD

**Issue by scitbiz** [anish000kumar/redux-box#6]
Can I use this library along with redux-persist? And how?

**Comment by anish000kumar** [comment]
You can use redux-persist or any library with redux-box the same way you did with redux.
From version 1.2.9 onwards you can use `{moduleToReducer} from 'redux-box'` to convert the module into a reducer.  thereafter you can pretty much follow redux-persist docs on how to persist  reducers. 

For persisting the store, here's the code borrowed from redux-persist with some modifications:

```javascript
import { moduleToReducer } from 'redux-box'
import {createStore} from 'redux'
import { persistStore, persistReducer } from 'redux-persist'
import storage from 'redux-persist/lib/storage'

import {module as userModule}  from './module/user'

const userReducer = moduleToReducer(userModule)
const persistConfig = {
  key: 'root',
  storage: storage,
}

const persistedReducer = persistReducer(persistConfig, userReducer)

export default () => {
  let store = createStore(persistedReducer)
  let persistor = persistStore(store)
  return { store, persistor }
}
```

**Comment by yordis** [comment]
@anish000kumar I would suggest to add as many code examples as possible that allow people to be  closer to Redux setup and see `redux-box` as something that you can progressly add

**Comment by anish000kumar** [comment]
@yordis  That's the attempt! The process would much faster if more contributors would show up and contribute examples of varying complexity. Here's the open issue in this regard: https://github.com/anish000kumar/redux-box/issues/3 
I guess you might contribute an example on using redux-persist to take the process a step forward!

**Comment by scitbiz** [comment]
@anish000kumar I've already upgraded to 1.2.9 but I cannot use `moduleToReducer` function (it said undefined)
And also I didn't see this function in your source code

**Comment by anish000kumar** [comment]
@scitbiz Seems `moduleToReducer` wasn't included in dist for 1.2.9. Should work with 1.3.0! Here's the working example for better reference: https://stackblitz.com/edit/react-pezrbb?file=store%2Findex.js for clearer

**Comment by scitbiz** [comment]
@anish000kumar  Awesome! And one more question: can I use `persistCombineReducers` function from redux-persist? And how?

**Comment by anish000kumar** [comment]
@scitbiz Can you share the docs for `persistCombineReducers` to let me see it's API

**Comment by scitbiz** [comment]
@anish000kumar you can see in here: https://github.com/rt2zz/redux-persist/blob/master/docs/MigrationGuide-v5.md

For example:
`
const persistConfig = {
  key: 'root',
  storage: storage,
}

const reducers = {
 firstReducer,
 secondReducer
}

persistCombineReducers(persistConfig, reducers)
`

**Comment by anish000kumar** [comment]
@scitbiz  this one works just fine :
```javascript
import {moduleToReducer} from 'redux-box'
import {createStore} from 'redux'
import {module as userModule} from './user'
import {module as cartModule} from './cart'
import { persistStore, persistReducer, persistCombineReducers } from 'redux-persist'
import storage from 'redux-persist/lib/storage'

const persistConfig = {
  key: 'root',
  storage: storage,
  whitelist: [ 'user' ]
}

const reducers ={
  user :  moduleToReducer(userModule),
  cart : moduleToReducer(cartModule)
}
const persistedReducer = persistCombineReducers(persistConfig, reducers)

export default createStore(persistedReducer)

```

**Comment by scitbiz** [comment]
@anish000kumar Is redux-saga declare in modules will work if we use
`import {createStore} from 'redux'` 
instead of
`import {createStore} from 'redux-box'` ?

**Comment by anish000kumar** [comment]
`{createStore} from 'redux-box'` handles sagas out of the box for you. However, if you use `{createStore} from 'redux'`, you will need to manually register sagas as well. Also, the signature of the two methods is different. I will be releasing a new version by tonight with the updated docs, showing how you can use something like `redux-persist` with much more ease.

**Comment by scitbiz** [comment]
@anish000kumar Thank you so much!

**Comment by anish000kumar** [comment]
@scitbiz 
In the latest version of redux-box, you can use redux-persisit like so:
```javascript
import {createStore} from 'redux-box';
import {module as homeModule} from './home'
import {module as userModule} from './user'
import {persistReducer, persistStore} from 'redux-persist'
import storage from 'redux-persist/lib/storage'

const modules = [homeModule, userModule]

const persistConfig = {
    key: 'root',
    storage,
    // blacklist: ['home'] //blacklist any module by it's name
}
const config = {
    decorateReducer : (reducer) => persistReducer(persistConfig, reducer)
}
const store = createStore(modules, config);
export const persistor = persistStore(store)

export default store;
```
